name: Sqitch Multi-Schema CI/CD

on:
  push:
    paths:
      - '**/*.sql'
      - '**/sqitch.plan'

jobs:
  sqitch-deploy:
    runs-on: ubuntu-latest
    container:
      image: sqitch/sqitch
    strategy:
      matrix:
        schema: [schema1, schema2, schema3]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy ${{ matrix.schema }}
        run: |
          cd ${{ matrix.schema }}
          sqitch deploy db:pg://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
