name: Sqitch CI/CD

on:
  push:
    paths:
      - '**/*.sql'
      - '**/sqitch.plan'
      - '**/.sqitch*'

jobs:
  sqitch-deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sqitch libdbd-pg-perl postgresql-client

      - name: Deploy all schemas via master-deploy
        run: |
          cd master-deploy/deploy
          bash deploy_all.sh
